repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
        args: [--exclude=games/.*\.py]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
